/******************************************************************************
*
* File:         SCMBuildStr.h
* Description:  Autogenerated header file with current build version string
*               -- generated by genverhdr.ksh in build-scripts
* Language:     C
*
*******************************************************************************/

#ifndef SCMBUILDSTR_H
#define SCMBUILDSTR_H 1

/* unused for now */
static const char * SCMBuildStr = "";

/* product version */
#define VERS_PV_MAJ 2
#define VERS_PV_MIN 7
#define VERS_PV_UPD 0

/* build version */
#define VERS_BR        c0d00fe_master
#define VERS_BR2       c0d00fe_dh_master
#define VERS_BR3       c0d00fe
#define VERS_BV        debug
#define VERS_SCMBV     esoye
#define VERS_SCMBV2    esoye

/* build date */
#define VERS_DT        03Oct22

/*prodver*/
#define VERS_PRODVER QianBase

/*copyright*/
#define COPYRIGHT  Copyright (c) 2015-2020 Esgyn Corporation

#endif

