#!/bin/bash
##############################################################################
##
## Install a sand-boxed version of Ampool, to be used together
## with the setup created in install_local_hadoop.
##
##############################################################################

# Root Location of Ampool 
AMPOOL_ROOT=${TRAF_HOME}/sql/scripts/ampool
mkdir -p ${AMPOOL_ROOT}

function Usage {
    echo 
    echo "Usage: $0 [ [-v <ver>] | -h ]"
    echo 
    echo "-v <version> Ampool version to be installed. E.g. -v 1.0.0"
    echo "-f           Force the install"
    echo "-i           Interactive"
    echo "-h           Help"
    echo
}

function GetOpts {
    while getopts "v:fhi" arg
      do
      case $arg in 
	  h)
	      Usage;
	      exit 1;
	      ;;
	  f)
	      AMPOOL_FORCE_INSTALL=y
	      ;;
	  i)
	      AMPOOL_INSTALL_TYPE=i
	      ;;
	  v)
              AMPOOL_VERSION=${OPTARG}
              ;;
      esac
    done
}

if [[ ! -d "${AMPOOL_ROOT}" ]]; then
  echo "Could not find the directory: ${AMPOOL_ROOT}"
  exit 1
fi

# Default ampool version (override using the -v option)
AMPOOL_VERSION=1.4.0
AMPOOL_INSTALL_TYPE="a"   # non-interactive install
AMPOOL_FORCE_INSTALL=n

GetOpts $*

if [ "${AMPOOL_INSTALL_TYPE}" = "i" ]; then
    echo "Going to install Ampool version: ${AMPOOL_VERSION}"
    echo -n "Is this ok? (y, (n)) "
    read YN
    
    if [ "$YN" = "n" -o "$YN" = "N" ]; then
	echo "Exiting";
	exit 1;
    fi
fi

# Download info for Ampool
AMPOOL_MIRROR_URL=https://s3-us-west-2.amazonaws.com/ampool-releases/${AMPOOL_VERSION}
AMPOOL_ID=ampool-${AMPOOL_VERSION}
AMPOOL_TAR=${AMPOOL_ID}.tar.gz
AMPOOL_DIR_NAME=ampool
AMPOOL_HOME=${AMPOOL_ROOT}/${AMPOOL_DIR_NAME}
AMPOOL_LOCATOR_PORT=10334
AMPOOL_SERVER_PORT=10344

if [[ -d ${AMPOOL_ROOT}/${AMPOOL_ID} ]]; then
    echo -n "Ampool is already installed at: ${AMPOOL_ROOT}/${AMPOOL_TAR}"
    if [ "${AMPOOL_FORCE_INSTALL}" = "n" ]; then
	echo "..exitting"
	exit 1
    else
	echo "..continuing (force_install)"
	rm ${AMPOOL_HOME}
    fi
fi

cd ${AMPOOL_ROOT}

if [ -f ${MY_LOCAL_SW_DIST}/${AMPOOL_TAR} ]; then
    cp -p ${MY_LOCAL_SW_DIST}/${AMPOOL_TAR} .
    echo "Copied Ampool tar file from: ${MY_LOCAL_SW_DIST}/${AMPOOL_TAR}"
else
    echo "Downloading Ampool tar file: ${AMPOOL_MIRROR_URL}/${AMPOOL_TAR}"
    curl -O ${AMPOOL_MIRROR_URL}/${AMPOOL_TAR}
    echo "Downloaded Ampool tar file: ${AMPOOL_MIRROR_URL}/${AMPOOL_TAR}"
fi

if [[ ! -f ${AMPOOL_TAR} ]]; then
    echo "Unable to download Ampool tar file ${AMPOOL_MIRROR_URL}/${AMPOOL_TAR}"
    exit 1
fi

tar -xzf ${AMPOOL_TAR}
ln -s ${AMPOOL_ID} ${AMPOOL_DIR_NAME}

# pick up environment variables with the relevant port numbers
. ${TRAF_HOME}/sql/scripts/sw_env.sh

AMPOOL_LOCATOR_PORT=`expr ${MY_HADOOP_HDFS_PORT_NUM} + 110`
AMPOOL_SERVER_PORT=`expr ${AMPOOL_LOCATOR_PORT} + 10`

cat <<EOF >${AMPOOL_ROOT}/setup_ampool_env
AMPOOL_LOCATOR_PORT=${AMPOOL_LOCATOR_PORT}
AMPOOL_SERVER_PORT=${AMPOOL_SERVER_PORT}

AMPOOL_LOCATOR=locator
AMPOOL_SERVER=server

export AMPOOL_HOME=${AMPOOL_ROOT}/ampool
export AMPOOL_VERSION=${AMPOOL_VERSION}
export AMPOOL_SCRIPTS=${TRAF_HOME}/sql/scripts/ampool
export AMPOOL_DBLOC=${AMPOOL_ROOT}/data
EOF

JMX_MANAGER_PORT=`expr ${AMPOOL_LOCATOR_PORT} - 1`
HTTP_SERVICE_PORT=`expr ${AMPOOL_LOCATOR_PORT} - 2`
cat <<EOF >${AMPOOL_ROOT}/ampool_locator.properties

jmx-manager-port=${JMX_MANAGER_PORT}
http-service-port=${HTTP_SERVICE_PORT}
jmx-manager=true 
jmx-manager-start=true

EOF

# customize the embedded Ampool configuration to use custom
# port numbers and files local to ${AMPOOL_ROOT}
AMPOOL_CONFIG_FILE=${AMPOOL_HOME}/config/ampool-site.xml
cat <<EOF >${AMPOOL_CONFIG_FILE}
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
<configuration>
    <property>
        <name>ampool.monarch.locator.port</name>
        <value>${AMPOOL_LOCATOR_PORT}</value>
        <description>Specifies the port on which Monarch Locator service will Run</description>
    </property>
    <property>
        <name>ampool.monarch.locator.address</name>
        <value>localhost</value>
        <description>Specifies the address on which Monarch Locator service will Run</description>
    </property>
</configuration>
EOF

cd ${TRAF_HOME}/conf
ln -s -f ${AMPOOL_CONFIG_FILE}
cd -

AMPOOL_INSTALL_INFO="${AMPOOL_ROOT}/ampool_install_info"
cat <<EOF > ${AMPOOL_INSTALL_INFO}
install_local_ampool: `date`
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
A local copy of Ampool has been installed. Here is some info.

- Install location: ${AMPOOL_HOME}
- Ampool Data Directory: ${AMPOOL_DBLOC}
- ampool-site.xml: ${AMPOOL_CONFIG_FILE}

-------------------------------------------------------------------------------

Here are a few esgyn scripts:

- ampool_startup: Starts ampool and configures the Esgyn transactional coprocessor
- ampool_shutdown: Shuts down ampool
- ampool_restart: Convenience script to shut down and then immediately start up ampool
- ampool_status: Check the status of ampool
- ampool_mash: Starts the mash utility
               At the mash prompt, please issue the following to connect with the locator:
                  connect --locator=localhost[${AMPOOL_LOCATOR_PORT}]
- ampool_cleanup: Cleans up the ampool database
- uninstall_local_ampool: Shuts down ampool and uninstalls it.

-------------------------------------------------------------------------------

To be able to connect to ampool from Esgyn DB, please:
- sqstop
- start a new term
- rm $TRAF_VAR/ms.env
- sqgen
- ampool_startup
- sqstart

-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
EOF

cat ${AMPOOL_INSTALL_INFO}
echo "The above info has been saved in the file: ${AMPOOL_INSTALL_INFO}"

exit 0
