
// -----------------------------------------------------------------------
// Files in the common directory that are needed by the CLI, by ARKESP,
// and by the components below. Don't add any files that have dependencies
// to outside components to this list.
// -----------------------------------------------------------------------
#include "BaseTypes.cpp"
#include "ComDistribution.cpp"
#include "ComGuardianFileNameParts.cpp"
#include "ComMvAttributeBitmap.cpp"
#include "ComRtUtils.cpp"
#include "ComSpace.cpp"
#include "ComSqlId.cpp"
#include "ComSysUtils.cpp"
#include "ComTransInfo.cpp"
#include "ComVersionNodeInfo.cpp"
#include "ComVersionPrivate.cpp"
#include "ComVersionPublic.cpp"
#include "DgBaseType.cpp"
#include "ErrorCondition.cpp"
#include "Ipc.cpp"
#include "IpcGuardian.cpp"
#include "IpcSockets.cpp"
#include "NAAssert.cpp"
#include "NAMemory.cpp"
#include "charinfo.cpp"
#include "conversionISO88591.cpp"
#include "conversionKSC5601.cpp"
#include "conversionLocale.cpp"
#include "conversionSJIS.cpp"
#include "long.cpp"
#include "str.cpp"
#include "unicode_char_set.cpp"
#include "wstr.cpp"
//#include "NLSConversion.cpp"
#include "ComResWords.cpp"
#include "ComplexObject.cpp"
#include "NAString2.cpp"
#include "stringBuf.cpp"
