CREATE EXTERNAL TABLE SHIP_MODE
  ( 
    SM_SHIP_MODE_SK                  INT DEFAULT NULL NOT SERIALIZED
  , SM_SHIP_MODE_ID                  VARCHAR(16) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , SM_TYPE                          VARCHAR(30) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , SM_CODE                          VARCHAR(10) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , SM_CARRIER                       VARCHAR(20) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , SM_CONTRACT                      VARCHAR(20) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  )
  FOR HIVE.TPCDS_SF1000.SHIP_MODE
;
CREATE EXTERNAL TABLE STORE_SALES
  FOR HIVE.TPCDS_SF1000.STORE_SALES
;
CREATE EXTERNAL TABLE WEB_RETURNS
  FOR HIVE.TPCDS_SF1000.WEB_RETURNS
;
CREATE EXTERNAL TABLE HOUSEHOLD_DEMOGRAPHICS
  ( 
    HD_DEMO_SK                       INT DEFAULT NULL NOT SERIALIZED
  , HD_INCOME_BAND_SK                INT DEFAULT NULL NOT SERIALIZED
  , HD_BUY_POTENTIAL                 VARCHAR(15) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , HD_DEP_COUNT                     INT DEFAULT NULL NOT SERIALIZED
  , HD_VEHICLE_COUNT                 INT DEFAULT NULL NOT SERIALIZED
  )
  FOR HIVE.TPCDS_SF1000.HOUSEHOLD_DEMOGRAPHICS
;
CREATE EXTERNAL TABLE WAREHOUSE
  ( 
    W_WAREHOUSE_SK                   INT DEFAULT NULL NOT SERIALIZED
  , W_WAREHOUSE_ID                   VARCHAR(16) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , W_WAREHOUSE_NAME                 VARCHAR(20) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , W_WAREHOUSE_SQ_FT                INT DEFAULT NULL NOT SERIALIZED
  , W_STREET_NUMBER                  VARCHAR(10) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , W_STREET_NAME                    VARCHAR(60) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , W_STREET_TYPE                    VARCHAR(15) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , W_SUITE_NUMBER                   VARCHAR(10) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , W_CITY                           VARCHAR(60) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , W_COUNTY                         VARCHAR(30) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , W_STATE                          VARCHAR(2) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , W_ZIP                            VARCHAR(10) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , W_COUNTRY                        VARCHAR(20) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , W_GMT_OFFSET                     REAL DEFAULT NULL NOT SERIALIZED
  )
  FOR HIVE.TPCDS_SF1000.WAREHOUSE
;
CREATE EXTERNAL TABLE STORE
  ( 
    S_STORE_SK                       INT DEFAULT NULL NOT SERIALIZED
  , S_STORE_ID                       VARCHAR(31999 BYTES) CHARACTER SET UTF8
      COLLATE DEFAULT DEFAULT NULL NOT SERIALIZED
  , S_REC_START_DATE                 DATE DEFAULT NULL NOT SERIALIZED
  , S_REC_END_DATE                   DATE DEFAULT NULL NOT SERIALIZED
  , S_CLOSED_DATE_SK                 INT DEFAULT NULL NOT SERIALIZED
  , S_STORE_NAME                     VARCHAR(50) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , S_NUMBER_EMPLOYEES               INT DEFAULT NULL NOT SERIALIZED
  , S_FLOOR_SPACE                    INT DEFAULT NULL NOT SERIALIZED
  , S_HOURS                          VARCHAR(20) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , S_MANAGER                        VARCHAR(40) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , S_MARKET_ID                      INT DEFAULT NULL NOT SERIALIZED
  , S_GEOGRAPHY_CLASS                VARCHAR(100) CHARACTER SET ISO88591
      COLLATE DEFAULT DEFAULT NULL NOT SERIALIZED
  , S_MARKET_DESC                    VARCHAR(100) CHARACTER SET ISO88591
      COLLATE DEFAULT DEFAULT NULL NOT SERIALIZED
  , S_MARKET_MANAGER                 VARCHAR(40) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , S_DIVISION_ID                    INT DEFAULT NULL NOT SERIALIZED
  , S_DIVISION_NAME                  VARCHAR(50) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , S_COMPANY_ID                     INT DEFAULT NULL NOT SERIALIZED
  , S_COMPANY_NAME                   VARCHAR(50) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , S_STREET_NUMBER                  VARCHAR(10) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , S_STREET_NAME                    VARCHAR(60) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , S_STREET_TYPE                    VARCHAR(15) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , S_SUITE_NUMBER                   VARCHAR(10) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , S_CITY                           VARCHAR(60) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , S_COUNTY                         VARCHAR(30) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , S_STATE                          VARCHAR(2) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , S_ZIP                            VARCHAR(10) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , S_COUNTRY                        VARCHAR(20) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , S_GMT_OFFSET                     REAL DEFAULT NULL NOT SERIALIZED
  , S_TAX_PERCENTAGE                 REAL DEFAULT NULL NOT SERIALIZED
  )
  FOR HIVE.TPCDS_SF1000.STORE
;
CREATE EXTERNAL TABLE CUSTOMER
  ( 
    C_CUSTOMER_SK                    INT DEFAULT NULL NOT SERIALIZED
  , C_CUSTOMER_ID                    VARCHAR(16) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , C_CURRENT_CDEMO_SK               INT DEFAULT NULL NOT SERIALIZED
  , C_CURRENT_HDEMO_SK               INT DEFAULT NULL NOT SERIALIZED
  , C_CURRENT_ADDR_SK                INT DEFAULT NULL NOT SERIALIZED
  , C_FIRST_SHIPTO_DATE_SK           INT DEFAULT NULL NOT SERIALIZED
  , C_FIRST_SALES_DATE_SK            INT DEFAULT NULL NOT SERIALIZED
  , C_SALUTATION                     VARCHAR(10) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , C_FIRST_NAME                     VARCHAR(20) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , C_LAST_NAME                      VARCHAR(30) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , C_PREFERRED_CUST_FLAG            VARCHAR(1) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , C_BIRTH_DAY                      INT DEFAULT NULL NOT SERIALIZED
  , C_BIRTH_MONTH                    INT DEFAULT NULL NOT SERIALIZED
  , C_BIRTH_YEAR                     INT DEFAULT NULL NOT SERIALIZED
  , C_BIRTH_COUNTRY                  VARCHAR(20) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , C_LOGIN                          VARCHAR(13) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , C_EMAIL_ADDRESS                  VARCHAR(50) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , C_LAST_REVIEW_DATE_SK            INT DEFAULT NULL NOT SERIALIZED
  )
  FOR HIVE.TPCDS_SF1000.CUSTOMER
;
CREATE EXTERNAL TABLE INCOME_BAND
  FOR HIVE.TPCDS_SF1000.INCOME_BAND
;
CREATE EXTERNAL TABLE ITEM
  ( 
    I_ITEM_SK                        INT DEFAULT NULL NOT SERIALIZED
  , I_ITEM_ID                        VARCHAR(16) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , I_REC_START_DATE                 DATE DEFAULT NULL NOT SERIALIZED
  , I_REC_END_DATE                   DATE DEFAULT NULL NOT SERIALIZED
  , I_ITEM_DESC                      VARCHAR(200) CHARACTER SET ISO88591
      COLLATE DEFAULT DEFAULT NULL NOT SERIALIZED
  , I_CURRENT_PRICE                  REAL DEFAULT NULL NOT SERIALIZED
  , I_WHOLESALE_COST                 REAL DEFAULT NULL NOT SERIALIZED
  , I_BRAND_ID                       INT DEFAULT NULL NOT SERIALIZED
  , I_BRAND                          VARCHAR(50) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , I_CLASS_ID                       INT DEFAULT NULL NOT SERIALIZED
  , I_CLASS                          VARCHAR(50) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , I_CATEGORY_ID                    INT DEFAULT NULL NOT SERIALIZED
  , I_CATEGORY                       VARCHAR(50) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , I_MANUFACT_ID                    INT DEFAULT NULL NOT SERIALIZED
  , I_MANUFACT                       VARCHAR(50) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , I_SIZE                           VARCHAR(20) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , I_FORMULATION                    VARCHAR(20) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , I_COLOR                          VARCHAR(20) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , I_UNITS                          VARCHAR(10) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , I_CONTAINER                      VARCHAR(10) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , I_MANAGER_ID                     INT DEFAULT NULL NOT SERIALIZED
  , I_PRODUCT_NAME                   VARCHAR(50) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  )
  FOR HIVE.TPCDS_SF1000.ITEM
;
CREATE EXTERNAL TABLE WEB_SITE
  ( 
    WEB_SITE_SK                      INT DEFAULT NULL NOT SERIALIZED
  , WEB_SITE_ID                      VARCHAR(16) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , WEB_REC_START_DATE               DATE DEFAULT NULL NOT SERIALIZED
  , WEB_REC_END_DATE                 DATE DEFAULT NULL NOT SERIALIZED
  , WEB_NAME                         VARCHAR(50) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , WEB_OPEN_DATE_SK                 INT DEFAULT NULL NOT SERIALIZED
  , WEB_CLOSE_DATE_SK                INT DEFAULT NULL NOT SERIALIZED
  , WEB_CLASS                        VARCHAR(50) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , WEB_MANAGER                      VARCHAR(40) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , WEB_MKT_ID                       INT DEFAULT NULL NOT SERIALIZED
  , WEB_MKT_CLASS                    VARCHAR(50) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , WEB_MKT_DESC                     VARCHAR(100) CHARACTER SET ISO88591
      COLLATE DEFAULT DEFAULT NULL NOT SERIALIZED
  , WEB_MARKET_MANAGER               VARCHAR(40) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , WEB_COMPANY_ID                   INT DEFAULT NULL NOT SERIALIZED
  , WEB_COMPANY_NAME                 VARCHAR(50) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , WEB_STREET_NUMBER                VARCHAR(10) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , WEB_STREET_NAME                  VARCHAR(60) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , WEB_STREET_TYPE                  VARCHAR(15) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , WEB_SUITE_NUMBER                 VARCHAR(10) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , WEB_CITY                         VARCHAR(60) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , WEB_COUNTY                       VARCHAR(30) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , WEB_STATE                        VARCHAR(2) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , WEB_ZIP                          VARCHAR(10) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , WEB_COUNTRY                      VARCHAR(20) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , WEB_GMT_OFFSET                   REAL DEFAULT NULL NOT SERIALIZED
  , WEB_TAX_PERCENTAGE               REAL DEFAULT NULL NOT SERIALIZED
  )
  FOR HIVE.TPCDS_SF1000.WEB_SITE
;
CREATE EXTERNAL TABLE CUSTOMER_ADDRESS
  ( 
    CA_ADDRESS_SK                    INT DEFAULT NULL NOT SERIALIZED
  , CA_ADDRESS_ID                    VARCHAR(16) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , CA_STREET_NUMBER                 VARCHAR(10) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , CA_STREET_NAME                   VARCHAR(60) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , CA_STREET_TYPE                   VARCHAR(15) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , CA_SUITE_NUMBER                  VARCHAR(10) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , CA_CITY                          VARCHAR(60) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , CA_COUNTY                        VARCHAR(30) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , CA_STATE                         VARCHAR(2) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , CA_ZIP                           VARCHAR(10) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , CA_COUNTRY                       VARCHAR(20) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , CA_GMT_OFFSET                    REAL DEFAULT NULL NOT SERIALIZED
  , CA_LOCATION_TYPE                 VARCHAR(20) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  )
  FOR HIVE.TPCDS_SF1000.CUSTOMER_ADDRESS
;
CREATE EXTERNAL TABLE CATALOG_SALES
  FOR HIVE.TPCDS_SF1000.CATALOG_SALES
;
CREATE EXTERNAL TABLE CALL_CENTER
  ( 
    CC_CALL_CENTER_SK                INT DEFAULT NULL NOT SERIALIZED
  , CC_CALL_CENTER_ID                VARCHAR(16) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , CC_REC_START_DATE                DATE DEFAULT NULL NOT SERIALIZED
  , CC_REC_END_DATE                  DATE DEFAULT NULL NOT SERIALIZED
  , CC_CLOSED_DATE_SK                INT DEFAULT NULL NOT SERIALIZED
  , CC_OPEN_DATE_SK                  INT DEFAULT NULL NOT SERIALIZED
  , CC_NAME                          VARCHAR(50) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , CC_CLASS                         VARCHAR(50) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , CC_EMPLOYEES                     INT DEFAULT NULL NOT SERIALIZED
  , CC_SQ_FT                         INT DEFAULT NULL NOT SERIALIZED
  , CC_HOURS                         VARCHAR(20) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , CC_MANAGER                       VARCHAR(40) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , CC_MKT_ID                        INT DEFAULT NULL NOT SERIALIZED
  , CC_MKT_CLASS                     VARCHAR(50) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , CC_MKT_DESC                      VARCHAR(100) CHARACTER SET ISO88591
      COLLATE DEFAULT DEFAULT NULL NOT SERIALIZED
  , CC_MARKET_MANAGER                VARCHAR(40) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , CC_DIVISION                      INT DEFAULT NULL NOT SERIALIZED
  , CC_DIVISION_NAME                 VARCHAR(50) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , CC_COMPANY                       INT DEFAULT NULL NOT SERIALIZED
  , CC_COMPANY_NAME                  VARCHAR(50) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , CC_STREET_NUMBER                 VARCHAR(10) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , CC_STREET_NAME                   VARCHAR(60) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , CC_STREET_TYPE                   VARCHAR(15) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , CC_SUITE_NUMBER                  VARCHAR(10) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , CC_CITY                          VARCHAR(60) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , CC_COUNTY                        VARCHAR(30) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , CC_STATE                         VARCHAR(2) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , CC_ZIP                           VARCHAR(10) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , CC_COUNTRY                       VARCHAR(20) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , CC_GMT_OFFSET                    REAL DEFAULT NULL NOT SERIALIZED
  , CC_TAX_PERCENTAGE                REAL DEFAULT NULL NOT SERIALIZED
  )
  FOR HIVE.TPCDS_SF1000.CALL_CENTER
;
CREATE EXTERNAL TABLE DATE_DIM_54
  FOR HIVE.TPCDS_SF1000.DATE_DIM_54
;
CREATE EXTERNAL TABLE CUSTOMER_DEMOGRAPHICS
  ( 
    CD_DEMO_SK                       INT DEFAULT NULL NOT SERIALIZED
  , CD_GENDER                        VARCHAR(1) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , CD_MARITAL_STATUS                VARCHAR(1) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , CD_EDUCATION_STATUS              VARCHAR(20) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , CD_PURCHASE_ESTIMATE             INT DEFAULT NULL NOT SERIALIZED
  , CD_CREDIT_RATING                 VARCHAR(10) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , CD_DEP_COUNT                     INT DEFAULT NULL NOT SERIALIZED
  , CD_DEP_EMPLOYED_COUNT            INT DEFAULT NULL NOT SERIALIZED
  , CD_DEP_COLLEGE_COUNT             INT DEFAULT NULL NOT SERIALIZED
  )
  FOR HIVE.TPCDS_SF1000.CUSTOMER_DEMOGRAPHICS
;
CREATE EXTERNAL TABLE PROMOTION
  ( 
    P_PROMO_SK                       INT DEFAULT NULL NOT SERIALIZED
  , P_PROMO_ID                       VARCHAR(16) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , P_START_DATE_SK                  INT DEFAULT NULL NOT SERIALIZED
  , P_END_DATE_SK                    INT DEFAULT NULL NOT SERIALIZED
  , P_ITEM_SK                        INT DEFAULT NULL NOT SERIALIZED
  , P_COST                           REAL DEFAULT NULL NOT SERIALIZED
  , P_RESPONSE_TARGET                INT DEFAULT NULL NOT SERIALIZED
  , P_PROMO_NAME                     VARCHAR(50) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , P_CHANNEL_DMAIL                  VARCHAR(1) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , P_CHANNEL_EMAIL                  VARCHAR(1) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , P_CHANNEL_CATALOG                VARCHAR(1) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , P_CHANNEL_TV                     VARCHAR(1) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , P_CHANNEL_RADIO                  VARCHAR(1) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , P_CHANNEL_PRESS                  VARCHAR(1) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , P_CHANNEL_EVENT                  VARCHAR(1) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , P_CHANNEL_DEMO                   VARCHAR(1) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , P_CHANNEL_DETAILS                VARCHAR(100) CHARACTER SET ISO88591
      COLLATE DEFAULT DEFAULT NULL NOT SERIALIZED
  , P_PURPOSE                        VARCHAR(15) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , P_DISCOUNT_ACTIVE                VARCHAR(1) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  )
  FOR HIVE.TPCDS_SF1000.PROMOTION
;
CREATE EXTERNAL TABLE REASON
  ( 
    R_REASON_SK                      INT DEFAULT NULL NOT SERIALIZED
  , R_REASON_ID                      VARCHAR(16) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , R_REASON_DESC                    VARCHAR(100) CHARACTER SET ISO88591
      COLLATE DEFAULT DEFAULT NULL NOT SERIALIZED
  )
  FOR HIVE.TPCDS_SF1000.REASON
;
CREATE EXTERNAL TABLE STORE_SALES_1STRIPEPERFILE
  FOR HIVE.TPCDS_SF1000.STORE_SALES_1STRIPEPERFILE
;
CREATE EXTERNAL TABLE CATALOG_PAGE
  ( 
    CP_CATALOG_PAGE_SK               INT DEFAULT NULL NOT SERIALIZED
  , CP_CATALOG_PAGE_ID               VARCHAR(16) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , CP_START_DATE_SK                 INT DEFAULT NULL NOT SERIALIZED
  , CP_END_DATE_SK                   INT DEFAULT NULL NOT SERIALIZED
  , CP_DEPARTMENT                    VARCHAR(50) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , CP_CATALOG_NUMBER                INT DEFAULT NULL NOT SERIALIZED
  , CP_CATALOG_PAGE_NUMBER           INT DEFAULT NULL NOT SERIALIZED
  , CP_DESCRIPTION                   VARCHAR(100) CHARACTER SET ISO88591
      COLLATE DEFAULT DEFAULT NULL NOT SERIALIZED
  , CP_TYPE                          VARCHAR(100) CHARACTER SET ISO88591
      COLLATE DEFAULT DEFAULT NULL NOT SERIALIZED
  )
  FOR HIVE.TPCDS_SF1000.CATALOG_PAGE
;
CREATE EXTERNAL TABLE INVENTORY
  FOR HIVE.TPCDS_SF1000.INVENTORY
;
CREATE EXTERNAL TABLE DATE_DIM
  ( 
    D_DATE_SK                        INT DEFAULT NULL NOT SERIALIZED
  , D_DATE_ID                        VARCHAR(16) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , D_DATE                           DATE DEFAULT NULL NOT SERIALIZED
  , D_MONTH_SEQ                      INT DEFAULT NULL NOT SERIALIZED
  , D_WEEK_SEQ                       INT DEFAULT NULL NOT SERIALIZED
  , D_QUARTER_SEQ                    INT DEFAULT NULL NOT SERIALIZED
  , D_YEAR                           INT DEFAULT NULL NOT SERIALIZED
  , D_DOW                            INT DEFAULT NULL NOT SERIALIZED
  , D_MOY                            INT DEFAULT NULL NOT SERIALIZED
  , D_DOM                            INT DEFAULT NULL NOT SERIALIZED
  , D_QOY                            INT DEFAULT NULL NOT SERIALIZED
  , D_FY_YEAR                        INT DEFAULT NULL NOT SERIALIZED
  , D_FY_QUARTER_SEQ                 INT DEFAULT NULL NOT SERIALIZED
  , D_FY_WEEK_SEQ                    INT DEFAULT NULL NOT SERIALIZED
  , D_DAY_NAME                       VARCHAR(9) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , D_QUARTER_NAME                   VARCHAR(6) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , D_HOLIDAY                        VARCHAR(1) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , D_WEEKEND                        VARCHAR(1) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , D_FOLLOWING_HOLIDAY              VARCHAR(1) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , D_FIRST_DOM                      INT DEFAULT NULL NOT SERIALIZED
  , D_LAST_DOM                       INT DEFAULT NULL NOT SERIALIZED
  , D_SAME_DAY_LY                    INT DEFAULT NULL NOT SERIALIZED
  , D_SAME_DAY_LQ                    INT DEFAULT NULL NOT SERIALIZED
  , D_CURRENT_DAY                    VARCHAR(1) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , D_CURRENT_WEEK                   VARCHAR(1) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , D_CURRENT_MONTH                  VARCHAR(1) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , D_CURRENT_QUARTER                VARCHAR(1) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , D_CURRENT_YEAR                   VARCHAR(1) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  )
  FOR HIVE.TPCDS_SF1000.DATE_DIM
;
CREATE EXTERNAL TABLE TIME_DIM
  ( 
    T_TIME_SK                        INT DEFAULT NULL NOT SERIALIZED
  , T_TIME_ID                        VARCHAR(16) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , T_TIME                           INT DEFAULT NULL NOT SERIALIZED
  , T_HOUR                           INT DEFAULT NULL NOT SERIALIZED
  , T_MINUTE                         INT DEFAULT NULL NOT SERIALIZED
  , T_SECOND                         INT DEFAULT NULL NOT SERIALIZED
  , T_AM_PM                          VARCHAR(2) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , T_SHIFT                          VARCHAR(20) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , T_SUB_SHIFT                      VARCHAR(20) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , T_MEAL_TIME                      VARCHAR(20) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  )
  FOR HIVE.TPCDS_SF1000.TIME_DIM
;
CREATE EXTERNAL TABLE STORE_RETURNS
  FOR HIVE.TPCDS_SF1000.STORE_RETURNS
;
CREATE EXTERNAL TABLE WEB_PAGE
  ( 
    WP_WEB_PAGE_SK                   INT DEFAULT NULL NOT SERIALIZED
  , WP_WEB_PAGE_ID                   VARCHAR(16) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , WP_REC_START_DATE                DATE DEFAULT NULL NOT SERIALIZED
  , WP_REC_END_DATE                  DATE DEFAULT NULL NOT SERIALIZED
  , WP_CREATION_DATE_SK              INT DEFAULT NULL NOT SERIALIZED
  , WP_ACCESS_DATE_SK                INT DEFAULT NULL NOT SERIALIZED
  , WP_AUTOGEN_FLAG                  VARCHAR(1) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , WP_CUSTOMER_SK                   INT DEFAULT NULL NOT SERIALIZED
  , WP_URL                           VARCHAR(100) CHARACTER SET ISO88591
      COLLATE DEFAULT DEFAULT NULL NOT SERIALIZED
  , WP_TYPE                          VARCHAR(50) CHARACTER SET ISO88591 COLLATE
      DEFAULT DEFAULT NULL NOT SERIALIZED
  , WP_CHAR_COUNT                    INT DEFAULT NULL NOT SERIALIZED
  , WP_LINK_COUNT                    INT DEFAULT NULL NOT SERIALIZED
  , WP_IMAGE_COUNT                   INT DEFAULT NULL NOT SERIALIZED
  , WP_MAX_AD_COUNT                  INT DEFAULT NULL NOT SERIALIZED
  )
  FOR HIVE.TPCDS_SF1000.WEB_PAGE
;
CREATE EXTERNAL TABLE WEB_SALES
  FOR HIVE.TPCDS_SF1000.WEB_SALES
;
CREATE EXTERNAL TABLE CATALOG_RETURNS
  FOR HIVE.TPCDS_SF1000.CATALOG_RETURNS
;
