#! /bin/bash
# @@@ START COPYRIGHT @@@
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
# @@@ END COPYRIGHT @@@

# Like the pattern-masking of QACOMP, here we filter out such stuff as
# transaction id.  Called by the runregr script before doing diff.

fil=$1
sed "
s/^\([ ]*PLAN_ID[ ]*[\.]*\) .*/\1 removed/g
s/^\([ ]*est_memory_per_node[ ]*[\.]*\) .*/\1 removed/g
s/\/\* ObjectUID = *[0-9]*/ObjectUID = <UID removed>/g
s/max_max_cardinality*[ ]*[\.]* .*/max_max_cardinality removed/g
s/^\(ROWS_OUT[ ]*[\.]*\) .*/ROWS_OUT... removed/g
s/max_card_est[ ]*[\.]* .*/max_card_est... removed/g
s/^\([ ]*EST_TOTAL_COST[ ]*[\.]*\) .*/EST_TOTAL_COST... removed/g
s/^\([ ]*EST_OPER_COST[ ]*[\.]*\) .*/EST_OPER_COST... removed/g
s/cache_size[ ]*[\.]* .*/cache_size... removed/g
s/rows_accessed[ ]*[\.]* .*/rows_accessed... removed/g
s/trafodion_scan[ ]*TBL.*/trafodion_scan TBL removed/g
s/merge_union .*/merge_union removed/g
s/\([^0-9]20[0-9][0-9][0-1][0-9][^0-9]\)\detected date/g
s/(TS >= [0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9] 00:00:00.000000) .*/(TS >= yyyy-mm-dd 00:00:00.000000)/g

" $fil
