#! /bin/bash


fil=$1
if [ "$fil" = "" ]; then
  echo "Usage: $0 filename"
  exit 1
fi

sed "
s/\(esp_exchange.*\)[1-9](hash2):[1-9]/\1 N(hash2):M/g
s/\(esp_exchange.*\)1:[1-9](hash2)/\1 1:N(hash2)/g
" $fil
