{
 "title": "Alert Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "DTM alert",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(esgyn_db_status_tm_configure) - sum(esgyn_db_status_tm)",
     "legendFormat": "Number of DTM"
    }
   ]
  },
  {
   "title": "Mxosrvr alert",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(esgyn_db_status_mxosrvr_configure) - sum(esgyn_db_status_mxosrvr)",
     "legendFormat": "Number of Mxosrvr"
    }
   ]
  },
  {
   "title": "RMS alert",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(esgyn_db_status_rms_configure) - sum(esgyn_db_status_rms)",
     "legendFormat": "Number of RMS"
    }
   ]
  },
  {
   "title": "DCS Master alert",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(esgyn_db_status_dcsm_configure) - sum(esgyn_db_status_dcsm)",
     "legendFormat": "Number of DCS Master"
    }
   ]
  },
  {
   "title": "Root directory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(1-(node_filesystem_free_bytes{mountpoint=\"/\", fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{mountpoint=\"/\", fstype=~\"ext4|xfs\"}))*100",
     "legendFormat": "Root directory usage"
    }
   ]
  },
  { "title": "Backup", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Import status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "esgyn_br_status_import", "legendFormat": "Import status" }
   ]
  },
  {
   "title": "Restore status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "esgyn_br_status_restore", "legendFormat": "Restore status" }
   ]
  },
  {
   "title": "Regular backup status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "esgyn_br_status_regular_backup", "legendFormat": "Regular backup status" }
   ]
  },
  {
   "title": "Regular export status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "esgyn_br_status_regular_export", "legendFormat": "Regular export status" }
   ]
  },
  {
   "title": "Incremental backup status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "esgyn_br_status_incr_backup", "legendFormat": "Incremental backup status" }
   ]
  },
  {
   "title": "Incremental export status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "esgyn_br_status_incr_export", "legendFormat": "Incremental export status" }
   ]
  }
 ]
}