{
 "title": "Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "主要进程状态",
   "type": "text",
   "description": "'OK'表示所有进程正常，红色数字表示当前未启动的进程数量",
   "gridPos": { "h": 1, "w": 3, "x": 0, "y": 1 },
   "content": "\n\n"
  },
  {
   "title": "集群健康度(1-100)",
   "type": "heatmap",
   "description": "根据磁盘，CPU，内存，数据库进程和数据库连接使用情况算出的健康度数值，范围(0-100)，供参考",
   "gridPos": { "h": 6, "w": 5, "x": 3, "y": 1 },
   "targets": [
    {
     "expr": "sum(esgyn_db_status_tm)/sum(esgyn_db_status_tm_configure) * (\n  avg(1-(node_filesystem_free_bytes{mountpoint=\"/\", fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{mountpoint=\"/\", fstype=~\"ext4|xfs\"})) * 15 + \n  (1 - avg(1 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m]))))) * 20 + \n  (1 - sum(node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes) / sum(node_memory_MemTotal_bytes)) * 25 + \n  sum(esgyn_active_sessions_available)/sum(esgyn_db_status_mxosrvr_configure) * 40 \n)"
    }
   ]
  },
  {
   "title": "HBase Regions 使用量",
   "type": "singlestat",
   "description": "每节点大于600region数黄色告警\n每节点大于800region数红色告警",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "target": "SELECT total_regions_across_regionservers/(total_regionservers_across_masters*1000)*100 WHERE entityName = \"hbase\" AND category = SERVICE"
    }
   ]
  },
  {
   "title": "集群CPU使用率",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100))"
    }
   ]
  },
  {
   "title": "集群内存使用率",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(1 - sum(node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes) / sum(node_memory_MemTotal_bytes)) * 100"
    },
    {}
   ]
  },
  {
   "title": "磁盘根目录已使用",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(1-(node_filesystem_free_bytes{mountpoint=\"/\", fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{mountpoint=\"/\", fstype=~\"ext4|xfs\"}))*100"
    }
   ]
  },
  {
   "title": "DTM",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(esgyn_db_status_tm_configure) - sum(esgyn_db_status_tm)"
    }
   ]
  },
  {
   "title": "Mxosrvr",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(esgyn_db_status_mxosrvr_configure) - sum(esgyn_db_status_mxosrvr)"
    }
   ]
  },
  {
   "title": "HDFS已使用",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "target": "select (dfs_capacity_used+dfs_capacity_used_non_hdfs)/dfs_capacity*100 where entityName=\"hdfs\" or entityName=\"hdfs:nameservice1\""
    }
   ]
  },
  {
   "title": "RMS",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(esgyn_db_status_rms_configure) - sum(esgyn_db_status_rms)"
    }
   ]
  },
  {
   "title": "集群在线节点数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 3, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(esgyn_db_status_tm)" }
   ]
  },
  {
   "title": "HBase Regions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 7 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "SELECT total_regions_across_regionservers WHERE entityName = \"hbase\" AND category = SERVICE"
    }
   ]
  },
  {
   "title": "Schema已使用",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 7 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    { "expr": "sum(esgyn_schema_usage)" }
   ]
  },
  {
   "title": "实时会话",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(esgyn_active_sessions_connected)"
    }
   ]
  },
  {
   "title": "ESP个数",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 7 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "sum(esgyn_db_status_esp)" }
   ]
  },
  {
   "title": "DCS Master",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(esgyn_db_status_dcsm_configure) - sum(esgyn_db_status_dcsm)"
    }
   ]
  },
  { "title": "QianBase", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "每分钟事务数 (TPM)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(esgyn_dtm_status_txnAborts[2m])/2",
     "legendFormat": "aborts"
    },
    {
     "expr": "increase(esgyn_dtm_status_txnBegins[2m])/2",
     "legendFormat": "begins"
    },
    {
     "expr": "increase(esgyn_dtm_status_txnCommits[2m])/2",
     "legendFormat": "commits"
    }
   ]
  },
  {
   "title": "每分钟SQL数 (QPM)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(esgyn_mxosrvr_total_completed_statements[2m]))/2",
     "legendFormat": "QPM"
    }
   ]
  },
  {
   "title": "已连接会话数",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "esgyn_active_sessions_connected",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Schema已使用空间",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 11 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    { "expr": "esgyn_schema_usage", "legendFormat": "{{schemaName}}" }
   ]
  },
  {
   "title": "QianBase core文件使用空间",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    { "expr": "esgyn_file_usage_esgyndb_core", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "QianBase日志目录使用空间",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    { "expr": "esgyn_file_usage_esgyndb_log", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Mxosrvr内存使用",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    { "expr": "esgyn_memory_usage_mxosrvr", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "System Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "内存使用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(1 - (node_memory_MemFree_bytes + node_memory_Cached_bytes + node_memory_Buffers_bytes) / node_memory_MemTotal_bytes) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU使用率（5m）",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 25 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "集群网络流量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "Bps", "label": "上传（-）/下载（+）" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{device!~'tap.*'}[5m]))",
     "legendFormat": "下载"
    },
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{device!~'tap.*'}[5m]))",
     "legendFormat": "上传"
    }
   ]
  },
  {
   "title": "集群磁盘读写数据量",
   "type": "graph",
   "description": "Read bytes 每个磁盘分区每秒读取的比特数\nWritten bytes 每个磁盘分区每秒写入的比特数",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 25 },
   "yaxes": [
    { "format": "Bps", "label": "读取（-）/写入（+）" }
   ],
   "targets": [
    {
     "expr": "sum(avg by (instance) (irate(node_disk_read_bytes_total[1m])))",
     "legendFormat": "读取"
    },
    {
     "expr": "sum(avg by (instance) (irate(node_disk_written_bytes_total[1m])))",
     "legendFormat": "写入"
    }
   ]
  },
  {
   "title": "系统平均负载(5m)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load5", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "当前打开的文件描述符",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_filefd_allocated", "legendFormat": "{{instance}}" },
    {}
   ]
  },
  {
   "title": "Swap分区使用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "node_memory_SwapFree_bytes / node_memory_SwapTotal_bytes",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Hadoop日志目录大小",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 33 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    { "expr": "esgyn_file_usage_hadoop_log", "legendFormat": "{{instance}}" }
   ]
  },
  { "title": "Hadoop Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "HDFS 容量",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "Bps", "label": "bytes" }
   ],
   "targets": [
    {
     "target": "select dfs_capacity, dfs_capacity_used, dfs_capacity_used_non_hdfs where entityName=\"hdfs\" or entityName=\"hdfs:nameservice1\""
    }
   ]
  },
  {
   "title": "HBase读请求数",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "short", "label": "requests / second" }
   ],
   "targets": [
    { "target": "select read_requests_rate" }
   ]
  },
  {
   "title": "HBase RS Heap使用量",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 42 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "target": "SELECT jvm_heap_used_mb_across_regionservers WHERE entityName = \"hbase\" AND category = SERVICE"
    }
   ]
  },
  {
   "title": "HDFS 读写",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "Bps", "label": "bytes / second" }
   ],
   "targets": [
    {
     "target": "SELECT  total_bytes_read_rate_across_datanodes, total_bytes_written_rate_across_datanodes WHERE entityName = \"hdfs\" AND category = SERVICE"
    }
   ]
  },
  {
   "title": "HBase写请求数",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 48 },
   "yaxes": [
    { "format": "short", "label": "requests / second" }
   ],
   "targets": [
    { "target": "select write_requests_rate" }
   ]
  },
  {
   "title": "HBase在线Region数",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 48 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "select regions where category=\"role\""
    }
   ]
  }
 ]
}