////
/**
* @@@ START COPYRIGHT @@@
*
* Licensed to the Apache Software Foundation (ASF) under one
* or more contributor license agreements.  See the NOTICE file
* distributed with this work for additional information
* regarding copyright ownership.  The ASF licenses this file
* to you under the Apache License, Version 2.0 (the
* "License"); you may not use this file except in compliance
* with the License.  You may obtain a copy of the License at
*
*   http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing,
* software distributed under the License is distributed on an
* "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
* KIND, either express or implied.  See the License for the
* specific language governing permissions and limitations
* under the License.
*
* @@@ END COPYRIGHT @@@
*/
////

[[generator-messages]]
= Generator Messages (7000 through 7999)

[[SQL-7001]]
== SQL 7001

```
Default value <value> is not valid for column <name>.
```

*Cause:* You attempted to create a table with an invalid default <value>
for column <name>.

*Effect:* The operation fails.

*Recovery:* Correct the syntax and resubmit.

[[SQL-7003]]
== SQL 7003

```
A plan using cluster sampling could not be produced for this query.
```

*Cause:* You can use cluster sampling in a query only on a base table
result set and only if there is no WHERE clause in the SELECT statement.
This query does not satisfy these conditions.

*Effect:* {project-name} is unable to compile the query.

*Recovery:* Rewrite the query (for example, using nested queries) so
that cluster sampling is performed on a base table with no WHERE-clause
predicate.

<<<
[[SQL-7030]]
== SQL 7030

```
Adaptive Segmentation: The provided settings for AS_AFFINITY_VALUE (<affinity>) 
and tenant size (<tenant-size>) as well as the number of nodes in the cluster 
(<cluster-size>) are not supported. Reason: <details>.
```

Where <affinity> is a value that identifies the subset of nodes to assign to the tenant.

Where <tenant-size> is the number of compute units defined for the tenant. 

Where <cluster-size> is the number of nodes available in the cluster.

Where <details> contains additional message text describing why the operation failed.

*Cause:* Adaptive segmentation assumes that the nodes are numbered 0 to n-1. 
When nodes are removed dynamically, the nodes may no longer be consecutively 
numbered. Therefore we introduce an additional step to map node ids to the 
actual physical node ids by using an affinity value, the cluster size and the 
tenant size. This error is returned because these values are incorrect. For 
example, if an incorrect cluster size is specified, <details> returns: 
"Size must be a positive integer". 

*Effect:* The operation fails.

*Recovery:* See <details> for a description of the problem.  Fix the problem and
retry the request.

[[SQL-7033]]
== SQL 7033

```
The specified nodes for the tenant of size <tenant-size> are not valid. Reason: <details>.
```

Where <tenant-size> is the number of compute units defined for the tenant. 

Where <details> contains additional message text describing why the operation failed.

*Cause:* The cause is specified in the <details>. Most likely this is
because the specified values for tenant size is incorrect as it applies to the
affinty and cluster size. For example, the <tenant-size> must be a factor or a
multiple of the cluster size.

*Effect:* The operation fails.

*Recovery:* See <details> for a description of the problem.  Fix the problem and
retry the request.

<<<
[[SQL-7034]]
== SQL 7034

```
Adaptive Segmentation: <affinity> is not a supported value for the AS_AFFINITY_VALUE CQD. 
Please use -4 (affinity based on master executor), -3 (affinity based on session id), 
-2 (Adaptive Segmentation off) or an integer affinity value >= 0
```

Where <affinity> is a value that identifies the subset of nodes to assign to the tenant.

*Cause:* Adaptive segmentation assumes that the nodes are numbered 0 to n-1. 
When nodes are removed dynamically, the nodes may no longer be consecutively 
numbered. Therefore we introduce an additional step to map node ids to the actual 
physical node ids used by using an affinity value, the cluster size and the 
tenant size.  This error is returned because an invalid affinity value is 
set for the control query default AS_AFFINITY_VALUE.

*Effect:* The operation fails.

*Recovery:* Please specify a correct affinity value for the control query default
AS_AFFINITY_VALUE and retry the request. 

