/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_hadoop_hbase_pit_XDC */

#ifndef _Included_org_apache_hadoop_hbase_pit_XDC
#define _Included_org_apache_hadoop_hbase_pit_XDC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_hadoop_hbase_pit_XDC
 * Method:    lockTMReq
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_apache_hadoop_hbase_pit_XDC_lockTMReq
  (JNIEnv *, jobject);

/*
 * Class:     org_apache_hadoop_hbase_pit_XDC
 * Method:    unlockTMReq
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_apache_hadoop_hbase_pit_XDC_unlockTMReq
  (JNIEnv *, jobject);

/*
 * Class:     org_apache_hadoop_hbase_pit_XDC
 * Method:    sdnTranReq
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_apache_hadoop_hbase_pit_XDC_sdnTranReq
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
