/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_trafodion_sql_HDFSClient */

#ifndef _Included_org_trafodion_sql_HDFSClient
#define _Included_org_trafodion_sql_HDFSClient
#ifdef __cplusplus
extern "C" {
#endif
#undef org_trafodion_sql_HDFSClient_UNCOMPRESSED
#define org_trafodion_sql_HDFSClient_UNCOMPRESSED 1L

#ifdef __cplusplus
}
#endif
#endif
