#!/usr/bin/env bash

if [[ $# != 0 ]]; then
    echo "usage: atrxdc_stop_replay"
    echo "description: stop binlog replayer, no parameters"
    exit 1
fi

lv_stderr_file="$TRAF_LOG/atrxdc.log"
atrxdc stop replayer 2>${lv_stderr_file}
atrxdc stop seqreplayer 2>${lv_stderr_file}
