#!/usr/bin/env bash

if [[ $# != 0 ]]; then
    echo "usage: atrxdc_start"
    echo "description: start atrxdc manager, worker(s) and replayer, no parameters"
    exit 1
fi

lv_stderr_file="$TRAF_LOG/atrxdc.log"
atrxdc_start_log_sync 2>${lv_stderr_file}
atrxdc_start_replay 2>${lv_stderr_file}
