#!/usr/bin/env bash

if [[ $# != 0 ]]; then
    echo "usage: atrxdc_stop"
    echo "description: stop atrxdc process, no parameters"
    exit 1
fi

lv_stderr_file="$TRAF_LOG/atrxdc.log"
atrxdc_stop_log_sync 2>${lv_stderr_file}
atrxdc_stop_replay 2>${lv_stderr_file}
