#!/usr/bin/env bash

if [[ $# != 0 ]]; then
    echo "usage: atrxdc_start"
    echo "description: start atrxdc manager and worker(s), no parameters"
    exit 1
fi

lv_stderr_file="$TRAF_LOG/atrxdc.log"
atrxdc start manager 2>${lv_stderr_file}

sleep 2

pname=`ps -af | grep AsyncXDCManager | grep -v grep`

if [[ $pname == "" ]]; then
    echo "Manager start failed"
    echo "look for details on $TRAF_LOG/"
else
    echo "Manager started:"
    atrxdc check
fi
