#!/usr/bin/env bash

if [[ $# != 0 ]]; then
    echo "usage: atrxdc_check"
    echo "description: check if atrxdc process running, no parameters"
    exit 1
fi

lv_stderr_file="$TRAF_LOG/atrxdc.log"
atrxdc check 2>${lv_stderr_file}
