#!/bin/bash
#
# @@@ START COPYRIGHT @@@
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
# @@@ END COPYRIGHT @@@
znode="/trafodion/recovery,/trafodion/splitbalance,/trafodion/traflock"
maxThread=500
opType="all"
tagTime=""
args=""
while [ -n "$*" ] ; do
  arg=$1
  shift
  case "$arg" in
    --ZNODE|-p)
      [ -n "$1" ] || error "Option --client requires an argument" 1
       znode=$1
      shift
      ;;
	 --MaxThread|-t)
      [ -n "$1" ] || error "Option --log requires an argument" 1
      maxThread=$1
      shift
      ;;
	 --opType|-op)
      [ -n "$1" ] || error "Option --log requires an argument" 1
      opType=$1
      shift
      ;;
     --tagTime|-tt)
      [ -n "$1" ] || error "Option --log requires an argument" 1
      tagTime=$1
      shift
      ;;
  esac
done
echo znode=${znode},maxThread=${maxThread},opType=${opType},tagTime=${tagTime} >> ${TRAF_LOG}/cleanZnode.log 2>&1 &

if [ -f $TRAF_HOME/sql/scripts/swzkcli ]
then swzkcli <<EOF
rmr /trafodion/recovery
rmr /trafodion/splitbalance
rmr /trafodion/traflock
EOF
else
 java -classpath $TRAF_HOME/export/lib/${ESGYN_SNMP_JAR}:$CLASSPATH com.esgyn.snmp.CleanZNode -n $znode -c $HBASE_CNF_DIR -p $maxThread -ts $tagTime -op $opType  >> ${TRAF_LOG}/cleanZnode.log 2>&1 &
fi


