#!/bin/bash
#
# @@@ START COPYRIGHT @@@
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
# @@@ END COPYRIGHT @@@
#

function Usage {
    echo "Usage: `basename $0` <-t <file> <-s <subject>> <-b <body-file>> [-v]"
    echo 
    echo "-t <file>     : <file> containing the list of recipient email addresses (one address per line)."
    echo "-s <subject>  : <subject> contains the subject of the email message."
    echo "-b <file>     : <file> containing the body of the email to be sent."
    echo "-v            : Verbose"
    echo "-h            : Help"
    echo
}

lv_to_list_file=""
lv_subject=""
declare -i lv_verbose=0

while getopts "t:s:b:vh" lv_arg $1 $2 $3 $4 $5 $6 $7 $8 $9
do
    case $lv_arg in 
	b)
	    lv_body_file=${OPTARG}
	    ;;
	s)
	    lv_subject=${OPTARG}
	    ;;
	t)
	    lv_to_list_file=${OPTARG}
	    ;;
	v)
	    let lv_verbose=1
	    ;;
	h)
	    lv_help=1
	    Usage
	    exit 0
            ;;
    esac
done

if [ -z ${lv_to_list_file} ]; then
    Usage
    exit 1
fi

if [ ${lv_verbose} '==' 1 ]; then
    echo "email address file: ${lv_to_list_file}"
    echo "email subject: ${lv_subject}"
    echo "email body file: ${lv_body_file}"
fi

lv_recipient_list=`cat ${lv_to_list_file}`
lv_ret=$?
if [ $lv_ret '!=' 0 ]; then
    echo "Error while retrieving the mail-to list from the file ${lv_to_list_file}"
    exit 1
fi

lv_to_list=""
for lv_recipient in ${lv_recipient_list} ; 
do
    if [ ! -z ${lv_to_list} ]; then
	lv_to_list+=","
    fi
    lv_to_list+=${lv_recipient}
done

if [ ${lv_verbose} '==' 1 ]; then
    echo ${lv_to_list}
fi

echo "sending email"
mail -s ${lv_subject} -b ${lv_to_list} edb@edb_notification < ${lv_body_file}

exit 0