#!/bin/bash

#
# Helper script used by sqcheck
#
# Get the current process status of all the processes required for sqcheck
#

egrep_cmd=dcs-$USER-master\|$USER-[0-9]*-\|dbmgr-.*.war\|^mxosrvr\|^tm\|^mxsscp\|^mxssmp

# Need to cut it else we sometimes lose some data
# Removed the 'a' parameter from 'ps axwww', 
# else it shows the processes for all the users on a shared workstation
cmd="ps xwww -u $USER -o cmd| cut -b 1-2000 | egrep '$egrep_cmd'|grep -v grep"

eval $cmd
