#!/bin/bash

if [ -z $TRAF_VAR ]; then
    echo
    echo "The TRAF_VAR environment variable does not exist."
    echo "Please ensure sqenv.sh has been sourced."
    echo
    exit 1;
fi

if [ ! -e ${TRAF_VAR}/ms.env ] ; then
    echo "File ${TRAF_VAR}/ms.env does not exist. Perhaps sqgen has not been executed on this cluster."
    echo "Exitting..."
    exit 1;
fi
echo "Checking for the environment variable TRAF_CLUSTER_ID=${lv_my_peer_id} (file: $TRAF_VAR/ms.env)"

lv_grep_output=`grep -w TRAF_CLUSTER_ID=.* $TRAF_VAR/ms.env`
lv_ret_status=$?
if [ $lv_ret_status '!=' 0 ]; then
    echo "Looks like an ID has not been assigned to this cluster. Please run \'add_my_cluster_id <id>\'"
else 
    echo "${lv_grep_output}"
    if [[ ${lv_grep_output:0:1} == '#' ]]; then
	echo "Looks like the variable has been commented out"
    fi
fi
