#!/bin/bash
#
# @@@ START COPYRIGHT @@@
#
# (C) Copyright 2018 Esgyn Corporation
#
# @@@ END COPYRIGHT @@@

if [[ -z "$(which sqshell 2>/dev/null)" ]]; then
	echo "Error:  Trafodion environment is not up."
	exit 1
fi

sqps | awk -f $TRAF_HOME/sql/scripts/jsqps.awk
