#!/bin/bash

MDS_BINARY="$TRAF_HOME/export/bin${SQ_MBTYPE}/mds"

if [ ! -f ${MDS_BINARY} ]; then
   echo "Mds binary cannot be found."
   exit 1;
fi

usage() {
    prog=`basename $0`
    echo "$prog { start | stop | restart | status }"
    echo "    start   -- start the Mds"
    echo "    stop    -- stop the Mds"
    echo "    restart -- restart the Mds"
    echo "    status  -- display the status of Mds"
}

mds_status() {
    act_mds_cnt=`edb_pdsh -a "ps -u $USER -ef |grep mds|grep -v grep|grep -v mds-client" 2>/dev/null|wc -l`
    let cfg_mds_cnt=`trafconf -nid-count`
    if [[ $act_mds_cnt -eq $cfg_mds_cnt ]]; then
        echo "$(date +%F_%T): Mds are running"
        return 0
    elif [[ $act_mds_cnt -eq 0 ]]; then
        echo "$(date +%F_%T): Mds are stopped"
        return 1
    elif [[ $act_mds_cnt -le $cfg_mds_cnt ]]; then
        echo "$(date +%F_%T): Mds are partially running: Configured[$cfg_mds_cnt]/Actual[$act_mds_cnt]"
        return 2
    else
        echo "$(date +%F_%T): Unknown status, please check the environment"
        return 3
    fi
}

mds_start() {
    mds_status
    rc=$?
    if [[ $rc -ne 0 ]]; then
        echo "$(date +%F_%T): Starting Mds ..."
        ${DCS_INSTALL_DIR}/bin/dcs-daemons.sh --config "${DCS_CONF_DIR}" --hosts "${TRAF_CONF}/dcs/servers" start mds
        echo "$(date +%F_%T): Started Mds"
    fi
}

mds_stop() {
    mds_status
    rc=$?
    if [[ $rc -ne 1 ]]; then
        echo "$(date +%F_%T): Stopping Mds ..."
        edb_pdsh -a "ps -u $USER -ef |grep mds|grep -v grep|grep -v mds-client|awk '{print \$2}'|xargs kill -9 2>/dev/null"
        echo "$(date +%F_%T): Stopped Mds"
    fi
}

case "$1" in
   start)
      mds_start
      ;;
   stop)
      mds_stop
      ;;
   restart)
      mds_stop
      mds_start
      ;;
   status)
      mds_status
      ;;
   *)
      usage
      exit 1
esac
exit 0