#!/bin/bash
MDS_FILE=$TRAF_CONF/dcs/mdsconf.yaml
ES_URL=`awk  '/esurl/ {print $2$3}' $MDS_FILE`

NUM=$1

function listall()
{
    curl -XGET "$ES_URL/mxosrvrs/_search" -H 'Content-Type: application/json' -d'
    {
        "query": {
            "match_all": {}
        },
        "sort" : [
            {"costtime" : "desc" }
        ]
    }'
}

function listN()
{
    curl -XGET "$ES_URL/mxosrvrs/_search" -H 'Content-Type: application/json' -d'
    {
        "query": {
        "match_all": {}
    },
    "sort" : [
        {"costtime" : "desc" }
    ],
        "size" : '$NUM'
    }'
}

if [[ $NUM -gt 0 ]];then
    listN
else
    listall
fi
