#!/bin/bash
# @@@ START COPYRIGHT @@@
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
# @@@ END COPYRIGHT @@@

if [[ $1 == "-m" ]]
then
  L_PDSH="eval"
  mode="node"
else
  L_PDSH="edb_pdsh -a"
  mode="cluster"
fi

uid="$(id -u)"

if [[ $mode == "cluster" ]]; then
   echo
   echo "Stopping DBMgr..."
   $L_PDSH $DBMGR_INSTALL_DIR/bin/dbmgr.sh stop
   $L_PDSH "pkill -9 -u $uid -f dbmgr" 2>/dev/null

fi

echo

