#!/bin/bash
#
# @@@ START COPYRIGHT @@@
#
# (C) Copyright 2019 Esgyn Corporation
#
# @@@ END COPYRIGHT @@@

OM_COMPONENT_COUNTS=3
ESGYN_EXPORTER_BINARY="$TRAF_HOME/export/bin${SQ_MBTYPE}/esgyn_exporter"
NODE_EXPORTER_BINARY="$TRAF_HOME/export/bin${SQ_MBTYPE}/node_exporter"
ESGYN_EXPORTER_PORT=23300
NODE_EXPORTER_PORT=23301

if [ ! -f ${ESGYN_EXPORTER_BINARY} ]; then
   echo "Esgyn Exporter binary cannot be found."
   exit 1;
fi

usage() {
    prog=`basename $0`
    echo "$prog { start | stop | restart | status }"
    echo "    start   -- start the OptMgmt client components: node_exporter/esgyn_exporter/filebeat"
    echo "    stop    -- stop the OptMgmt client components: node_exporter/esgyn_exporter/filebeat"
    echo "    restart -- restart the OptMgmt client components: node_exporter/esgyn_exporter/filebeat"
    echo "    status  -- display the status of OptMgmt client components: node_exporter/esgyn_exporter/filebeat"
}

om_start() {
    om_status
    rc=$?
    if [[ $rc -ne 0 ]]; then
        echo "$(date +%F_%T): Starting OptMgmt client components ..."
        edb_pdsh -a "mkdir -p $TRAF_LOG/mgblty/filebeat"
        edb_pdsh -a "$ESGYN_EXPORTER_BINARY --web.listen-address=\":$ESGYN_EXPORTER_PORT\"> $TRAF_LOG/mgblty/esgyn_exporter.log 2>&1 &"
        edb_pdsh -a "$NODE_EXPORTER_BINARY --web.listen-address=\":$NODE_EXPORTER_PORT\" > $TRAF_LOG/mgblty/node_exporter.log 2>&1 &"
        edb_pdsh -a "$MGBLTY_INSTALL_DIR/filebeat/filebeat --path.config=$TRAF_CONF/mgblty/filebeat/ --path.logs=$TRAF_LOG/mgblty/filebeat/ >/dev/null 2>$TRAF_LOG/mgblty/filebeat/filebeat-err.log &"
        echo "$(date +%F_%T): Started OptMgmt client components"
    fi
}

om_stop() {
    om_status
    rc=$?
    if [[ $rc -ne 1 ]]; then
        echo "$(date +%F_%T): Stopping OptMgmt client components ..."
        edb_pdsh -a "ps -u $USER -af |grep -E 'esgyn_exporter|node_exporter'|grep -v grep|awk '{print \$2}'|xargs kill 2>/dev/null"
        edb_pdsh -a "ps -u $USER -af |grep -E 'filebeat'|grep -v grep|awk '{print \$2}'|xargs kill -9 2>/dev/null"
        echo "$(date +%F_%T): Stopped OptMgmt client components"
    fi
}

om_status() {
    act_om_cnt=`edb_pdsh -a "ps -u $USER -af |grep -E 'esgyn_exporter|node_exporter|filebeat'|grep -v grep" 2>/dev/null|wc -l`
    let cfg_om_cnt=`trafconf -nid-count`*$OM_COMPONENT_COUNTS
    if [[ $act_om_cnt -eq $cfg_om_cnt ]]; then
        echo "$(date +%F_%T): OptMgmt client components are running"
        return 0
    elif [[ $act_om_cnt -eq 0 ]]; then
        echo "$(date +%F_%T): OptMgmt client components are stopped"
        return 1
    elif [[ $act_om_cnt -le $cfg_om_cnt ]]; then
        echo "$(date +%F_%T): OptMgmt client components are partially running: Configured[$cfg_om_cnt]/Actual[$act_om_cnt]"
        return 2
    else
        echo "$(date +%F_%T): Unknown status, please check the environment"
        return 3
    fi
}

case "$1" in
   start)
      om_start
      ;;
   stop)
      om_stop
      ;;
   restart)
      om_stop
      om_start
      ;;
   status)
      om_status
      ;;
   *)
      usage
      exit 1
esac
exit 0
