#!/bin/bash

# This script goes over evrey line from the output of 'ipcs -m' and looks
# for any segment that has not be destroyed 'dest'.  For each such segment, it
# schedules a removal of it via command ipcrm -m $shmid.

IFS=
input=`ipcs -m`
while read -r line
do
  columns=`echo $line | awk '{ print NF}'`
  #echo $columns

  if [ $columns = 6 ]; then
     #echo "$line"
     shmid=`echo $line | awk '{ print $2 }'`
     sizes=`echo $line | awk '{ print $5 }'`

     if [[ -z "$shmid" || $shmid == *[^[:digit:]]* ]]; then
       continue;
     fi
     echo "Perform ipcrm on segment: shmid="$shmid", bytes="$sizes
     ipcrm -m $shmid
  fi
done <<< $input

