#!/bin/bash

lv_pid=$(ps -ax | grep MySnmpTrapReceiver | grep -v grep | awk '{print $1;}')

if [ ${#lv_pid} '>' 0 ]; then
    echo "Killing the SNMP Trap Receiver process, pid: ${lv_pid}"
    kill -9 ${lv_pid}
    exit $?
else
    echo "Did not find any SNMP Trap Receiver process. Exiting"
    exit 1
fi
