#!/bin/bash
#
# @@@ START COPYRIGHT @@@
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
# @@@ END COPYRIGHT @@@
#

if [ $# != 1 ]; then
    echo -e "USAGE: $0 tid"
    echo 
    echo -e "  e.g: $0 72339086194607499"
    exit 0
fi
tid=$1

hex_tid=`printf "%x" ${tid}`

hex_cid=`echo ${hex_tid} | cut -b 1-3`
hex_nid=`echo ${hex_tid} | cut -b 4-7`
hex_xid=`echo ${hex_tid} | cut -b 8-`

cid=`printf "%d" 0x${hex_cid}`
nid=`printf "%d" 0x${hex_nid}`
xid=`printf "%d" 0x${hex_xid}`

echo "cid: ${cid} nid: ${nid} xid: ${xid}"
