#!/bin/bash
#
# @@@ START COPYRIGHT @@@
#
# (C) Copyright 2015-2016 Esgyn Corporation
#
# @@@ END COPYRIGHT @@@

if [ -z ${WMS_INSTALL_DIR} ]; then
   echo "WMS Install dir not found."
   exit 1;
fi
   actual_wms_cnt=`edb_pdsh -a "ps -ef |grep -v grep |grep wms_ |grep $USER" |wc -l`
   dcs_master_cnt=`edb_pdsh -a $JAVA_HOME/bin/jps |grep DcsMaster |wc -l`

if [[ ${dcs_master_cnt} > 0 ]]; then
  if [[ ${actual_wms_cnt} == 0 ]]; then
    echo "Starting WMS..."
    ${WMS_INSTALL_DIR}/bin/start-wms.sh
  else
    echo "WMS is up and running. Please stop it first..."
  fi
else
  echo "DcsMaster is not up. Please start dcs first..."
fi

echo
cds
