#! /bin/bash

# Specialized filter for  project to filter out
# 1. Syskey values
# 2. refreshed elapsed time
# 3. region names

fil=$1
if [ "$fil" = "" ]; then
  echo "Usage: $0 filename"
  exit 1
fi

sed "
s/\( *[0-9] *[0-9]\{3\} *[0-9]\{6\} *[0-9]\{3\} *[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\} *\)[0-9]*/\1@syskey@/
s/602[0-9]\{16,18\}/@syskey@/
s/2[0-9]\{16,18\}/@syskey@/
/^Task: /s/\(ET: \)[0-9][0-9]:[0-9][0-9]:[0-9][0-9]\\.[0-9]\\{3,\\}$/\1hh:mm:ss.xxx/
s/^\([ ]*RegionServer:[ ]*[\.]*\) .*/\1 RegionServer removed/g
s/^\([ ]*RegionName:[ ]*[\.]*\) .*/\1 RegionName removed/g
" $fil
