#!/bin/bash
# @@@ START COPYRIGHT @@@
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#
# @@@ END COPYRIGHT @@@

source cutils.sh
numdays=""

usage(){
     echo "
       This script lists core files and hs_err files 

      Usage: $0 [ -h | -c | -g <expression> ] 
      where  -h displays this help
             -c get the total count of files clusterwide
             -g <expression> to only list files with expresson specified
             -o list files that are older than n days. if '0' is specified it is the current day
     "
}

while getopts 'hco:g:' myOption;
do
   case "${myOption}" in
   h)  
       usage
       exit 0
       ;;
   c) 
       getTotalCnt
       exit 0
       ;;
   g) 
       coreFileName="core\.\*${OPTARG}\*"
       hsErrFileName="hs_err_pid\*${OPTARG}\*.log"
       echo "
       **** Getting files with pattern ${OPTARG} ****"
       ;;
   o) 
       numdays="${OPTARG}"
       echo "
       **** List of core files $numdays day(s) old ****"
       getOlderCoreFiles
       echo "
       **** List of hs_err files $numdays day(s) old ****"
       getOlderHsErrFiles
       getTotalCnt
       exit 0
       ;;
   ?) 
       echo "Invalid option specified. Only -h, -g, -o or -c are allowed"
       exit 0
       ;;
   esac
done

getListOfCoreFiles
getListOfHsErrFiles
getTotalCnt
exit 0
