#!/bin/bash
# @@@ START COPYRIGHT @@@
#
# (C) Copyright 2016 Esgyn Corportation
#
# @@@ END COPYRIGHT @@@

eval 'edb_pdsh -a $TRAF_HOME/tools/all_memory | sort'

echo
eval 'edb_pdsh -a $TRAF_HOME/tools/esgyn_memory | sort'

echo
eval 'edb_pdsh -a "$TRAF_HOME/tools/eproc_memory tm " | sort'

echo
eval 'edb_pdsh -a "$TRAF_HOME/tools/eproc_memory mxosrvr" | sort'

echo
eval 'edb_pdsh -a "$TRAF_HOME/tools/eproc_memory arkesp" | sort'

echo
eval 'edb_pdsh -a "$TRAF_HOME/tools/eproc_memory arkcmp" | sort'

echo
eval 'edb_pdsh -a "$TRAF_HOME/tools/eproc_memory monitor" | sort'

echo 
echo "Running 'vmstat -a' on each node. Memory is in MiB:"
# the following line just prints the vmstat header
vmstat -a | head -2 | sed -e "s/procs/\tprocs/" | sed -e "s/ r/\tr/"
eval 'edb_pdsh -a "vmstat -a -S M" | grep -v swpd | grep -v memory | sort'
