/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Hbase_TYPES_H
#define Hbase_TYPES_H

// #include <thrift/Thrift.h>
// #include <thrift/TApplicationException.h>
// #include <thrift/protocol/TProtocol.h>
// #include <thrift/transport/TTransport.h>



namespace apache { namespace hadoop { namespace hbase { namespace thrift {

typedef std::string Text;

typedef std::string Bytes;

typedef int32_t ScannerID;






}}}} // namespace

#endif
